# Forward problem (operator A) parameters
k: 11
sigma: 1.3
kernel_type: 'gaussian'

# Training parameters
learning_rate: 0.001
n_epochs: 30
batch_size: 12

# FiNN
finn:
  sigma: 1

# StNN
stnn:
  reg_param: 0.01
  n_iter: 3

# IS
is:
  reg_param: 0.08
  n_iter: 100